// The PlainTextExtractor against committed fixtures and hand-built bytes.
//
// The fixtures are generated by tool/make_fixtures.dart and committed; the
// bytes-level cases (BOMs, NUL heuristics, garbage refusal) are built inline
// so the test shows the exact encoding under test.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:test/test.dart';

import 'package:plan_extraction/plan_extraction.dart';

const extractor = PlainTextExtractor();

PickedBytes named(String fileName, List<int> bytes) => PickedBytes(
      fileName: fileName,
      extension: fileName.contains('.')
          ? fileName.split('.').last.toLowerCase()
          : null,
      bytes: Uint8List.fromList(bytes),
    );

void main() {
  ExtractionFailure asFailure(ExtractionResult result) {
    expect(result, isA<ExtractionFailure>());
    return result as ExtractionFailure;
  }

  group('decode ladder', () {
    test('UTF-8 without BOM decodes, emoji included', () {
      const text = 'Day 1 - Tokyo\n- Dinner at 一蘭 🍜\n';
      final result = extractor.extract(named('plan.txt', utf8.encode(text)));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, text);
    });

    test('UTF-8 BOM is stripped, not shown in the box', () {
      final result =
          extractor.extract(named('a.txt', [0xEF, 0xBB, 0xBF, ...utf8.encode('Day 1')]));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, 'Day 1');
    });

    test('UTF-16 LE with BOM', () {
      final units = 'Mon 14 June 2027 - Tokyo'.codeUnits;
      final bytes = <int>[0xFF, 0xFE];
      for (final u in units) {
        bytes..add(u & 0xFF)..add((u >> 8) & 0xFF);
      }
      final result = extractor.extract(named('w.txt', bytes));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, 'Mon 14 June 2027 - Tokyo');
    });

    test('UTF-16 BE with BOM', () {
      final units = 'Tue 15 June'.codeUnits;
      final bytes = <int>[0xFE, 0xFF];
      for (final u in units) {
        bytes..add((u >> 8) & 0xFF)..add(u & 0xFF);
      }
      final result = extractor.extract(named('w.txt', bytes));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, 'Tue 15 June');
    });

    test('UTF-16 LE without a BOM is found by the NUL heuristic', () {
      final units = 'Day 2 - Kyoto, plainly ascii prose here'.codeUnits;
      final bytes = <int>[];
      for (final u in units) {
        bytes..add(u & 0xFF)..add(0);
      }
      final result = extractor.extract(named('legacy.txt', bytes));
      expect(result, isA<ExtractedText>());
      expect(
        (result as ExtractedText).text,
        'Day 2 - Kyoto, plainly ascii prose here',
      );
    });

    test('Latin-1 fallback: é decodes from one byte', () {
      // "Café" with é as 0xE9.
      final bytes = [0x43, 0x61, 0x66, 0xE9, 0x0A];
      final result = extractor.extract(named('ansi.txt', bytes));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, 'Café\n');
    });

    test('Windows-1252 curly quotes decode instead of C1 controls', () {
      // “quoted” in cp1252: 0x93 ... 0x94.
      final bytes = [0x93, 0x68, 0x69, 0x94];
      final result = extractor.extract(named('word.txt', bytes));
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, '\u201Chi\u201D');
    });

    test('invalid UTF-8 that is also invalid Latin-1 prose still lands as '
        'something readable — the ladder never refuses honest prose', () {
      // Mixed UTF-8 fragment + high bytes: falls off the strict rung into
      // the wide rung and comes out readable rather than refused.
      final bytes = [...utf8.encode('Day 3 - '), 0xC3, 0x28, 0xE9, 0x0A];
      final result = extractor.extract(named('mixed.txt', bytes));
      expect(result, isA<ExtractedText>());
    });
  });

  group('refusals', () {
    test('empty file -> empty failure with the plan sentence', () {
      final result = extractor.extract(named('empty.txt', []));
      final failure = asFailure(result);
      expect(failure.kind, ExtractionFailureKind.empty);
      expect(
        failure.explanation,
        "That file didn't contain any text.",
      );
    });

    test('whitespace-only file -> empty failure too', () {
      final result = extractor.extract(named('blank.txt', utf8.encode('\n \t\n')));
      expect(asFailure(result).kind, ExtractionFailureKind.empty);
    });

    test('binary garbage wearing .txt -> unreadable, box stays clean', () {
      // JPEG magic plus pseudo-random high bytes: no valid UTF-8, control
      // flood after any decode.
      final junk = <int>[0xFF, 0xD8, 0xFF, 0xE0];
      final rng = 7919;
      var state = rng;
      for (var i = 0; i < 512; i++) {
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF;
        junk.add(state & 0xFF);
      }
      final result = extractor.extract(named('photo.txt', junk));
      final failure = asFailure(result);
      expect(failure.kind, ExtractionFailureKind.unreadable);
      expect(failure.explanation,
          "Couldn't read that file — it may be damaged or password-protected.");
    });

    test('known binary magic is refused even when ASCII-decodable', () {
      // %PDF- is plain ASCII, but a PDF is slice B's job, never ours.
      final result = extractor.extract(named('x.txt', utf8.encode('%PDF-1.7\n%âãÏÓ\n')));
      expect(asFailure(result).kind, ExtractionFailureKind.unreadable);
    });

    test('an oversized file is refused before reading', () {
      final big = Uint8List(maxPlainBytes + 1);
      big[0] = 0x44;
      final result = extractor.extract(named('big.txt', big));
      expect(
        (result as ExtractionFailure).explanation,
        contains('25 MB'),
      );
    });
  });

  group('routing contract', () {
    test('claims txt and matches honest text', () {
      expect(extractor.extensions, {'txt'});
      expect(
        extractor.matches(named('plan.txt', utf8.encode('Day 1 - Tokyo'))),
        isTrue,
      );
    });

    test('does not match known binary containers by magic', () {
      final zip = [0x50, 0x4B, 0x03, 0x04, 0x14, 0x00, 0x00, 0x00];
      expect(extractor.matches(named('plan.docx', zip)), isFalse);
      expect(extractor.matches(named('plan.pdf', utf8.encode('%PDF-1.6'))),
          isFalse);
    });

    test('never throws, whatever the bytes', () {
      // A sweep of adversarial byte shapes: the interface promises extract
      // cannot throw, and this is where that promise is pinned.
      final shapes = <List<int>>[
        [],
        [0x00],
        [0xFF, 0xFE],
        [0xFE, 0xFF],
        [0xEF, 0xBB],
        [0xD8, 0x00, 0xDC, 0x00], // unpaired surrogate trail
        List.filled(64, 0x00),
        List.filled(64, 0xFF),
        utf8.encode('Day 1'),
      ];
      for (final shape in shapes) {
        expect(
          () => extractor.extract(named('fuzz.txt', shape)),
          returnsNormally,
        );
      }
    });
  });

  group('committed fixtures round-trip through the parser', () {
    final fixtureNames = [
      'tidy-utf8.txt',
      'tidy-utf8-bom.txt',
      'tidy-crlf.txt',
      'tidy-utf16le-bom.txt',
      'tidy-utf16be-bom.txt',
      'cafe-latin1.txt',
    ];

    for (final name in fixtureNames) {
      test('$name extracts to the same lines whatever its encoding', () async {
        final bytes = File('test/fixtures/$name').readAsBytesSync();
        final result = extractor.extract(named(name, bytes));
        expect(result, isA<ExtractedText>(), reason: name);
        final text = (result as ExtractedText).text;

        // Every encoding of the tidy fixture must read back the same days:
        // two dated headers, four stops. This is the package's promise to
        // PasteFlow.parse() — the parser sees one truth per container.
        expect(text, contains('Mon 14 June 2027 - Tokyo'));
        expect(text, contains('Senso-ji at 9:00'));
        expect(text, contains('Ueno Park picnic'));
        expect(text, contains('Café stop on the way'));
        expect(text, contains('Tue 15 June 2027 - Kyoto'));
        expect(text, contains('Fushimi Inari at dawn'));
        expect('\n'.allMatches(text.trim()), hasLength(6));
      });
    }

    test('empty fixtures come back as the empty failure', () {
      for (final name in ['empty.txt', 'blank.txt']) {
        final bytes = File('test/fixtures/$name').readAsBytesSync();
        final result = extractor.extract(named(name, bytes));
        expect(asFailure(result).kind, ExtractionFailureKind.empty, reason: name);
      }
    });
  });

  group('short lines and long files', () {
    test('CRLF short lines are not mistaken for binary', () {
      const text = 'Day 1\r\nSenso-ji\r\nUeno Park\r\n';
      final picked = named('notepad.txt', utf8.encode(text));
      expect(extractor.matches(picked), isTrue);
      final result = extractor.extract(picked);
      expect(result, isA<ExtractedText>());
      expect((result as ExtractedText).text, 'Day 1\nSenso-ji\nUeno Park\n');
    });

    test('lone CR line endings read as lines too', () {
      final picked = named('classic.txt', utf8.encode('Day 1\rSenso-ji\rUeno\r'));
      expect(extractor.matches(picked), isTrue);
      final result = extractor.extract(picked);
      expect((result as ExtractedText).text, 'Day 1\nSenso-ji\nUeno\n');
    });

    test('routing sniffs a prefix, so a huge file still claims and refuses', () {
      final bytes = utf8.encode('Day 1 - Tokyo\r\n' * 3000000);
      expect(bytes.length, greaterThan(maxPlainBytes));
      final picked = named('huge.txt', bytes);
      expect(extractor.matches(picked), isTrue);
      final failure = asFailure(extractor.extract(picked));
      expect(failure.kind, ExtractionFailureKind.unreadable);
      expect(failure.explanation, contains('25 MB'));
    });

    test('a huge binary file is still refused by the prefix sniff', () {
      final bytes = <int>[
        ...utf8.encode('%PDF-1.7'),
        ...List.filled(30 * 1024 * 1024, 0x01),
      ];
      expect(extractor.matches(named('huge.txt', bytes)), isFalse);
    });
  });
}
